package com.example.madproject

import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity
import android.widget.*
import androidx.lifecycle.lifecycleScope
import io.github.jan.supabase.postgrest.from
import io.ktor.client.*
import io.ktor.client.engine.android.*
import io.ktor.client.request.*
import io.ktor.client.statement.*
import kotlinx.coroutines.launch
import org.json.JSONArray

/**
 * AddWordActivity allows the user to log their words
 * Looks up the meaning using the Dictionary API
 * Saves the word, meaning and book to Supabase
 */
class AddWordActivity : AppCompatActivity() {

    //Ktor HTTP client for calling the dictionary API
    private val httpClient = HttpClient(Android)

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_add_word)

        // Bind UI elements from the layout
        val wordInput = findViewById<EditText>(R.id.wordInput)
        val bookInput = findViewById<EditText>(R.id.bookInput)
        val saveButton = findViewById<Button>(R.id.saveWord)
        val wordMeaningText = findViewById<TextView>(R.id.wordMeaning)

        // Triggered when the user taps the save button
        saveButton.setOnClickListener {
            val word = wordInput.text.toString().trim()
            val book = bookInput.text.toString().trim()

            //Basic validation
            if (word.isEmpty() || book.isEmpty()) {
                Toast.makeText(
                    this,
                    "Please fill in all fields",
                    Toast.LENGTH_SHORT).show()
                return@setOnClickListener
            }

            // Launch coroutine on lifecycle scope so it cancels if the Activity is destroyed
            lifecycleScope.launch {
                try {
                    // Call the free dictionary API with the entered word
                    val response: HttpResponse = httpClient.get(
                        "https://api.dictionaryapi.dev/api/v2/entries/en/$word"
                    )
                    val bodyText = response.bodyAsText()

                    //Parse the first meaning from the JSON response
                    val meaning = parseMeaning(bodyText)

                    // Save the word, meaning, and book to the Supabase "words" table
                    // word_id and timestamp are auto-generated by Supabase
                    SupabaseClientProvider.client.from("words").insert(
                        Word(
                            wordText = word,
                            wordMeaning = meaning,
                            bookFoundIn = book
                        )
                    )

                    //show the user the meaning
                    wordMeaningText.text = "Meaning: $meaning"
                    Toast.makeText(this@AddWordActivity, "Word Saved!", Toast.LENGTH_SHORT).show()
                } catch (e: Exception) {
                    android.util.Log.e("AddWordError", "Failed", e)
                    Toast.makeText(
                        this@AddWordActivity,
                        "Failed: ${e.message}",
                        Toast.LENGTH_LONG
                    ).show()
                }
            }
        }
    }

    /**
     * Parse meaning stuff down here, idk where else to put it
     * GRabs the first meaning (will add more logic to find the right one later)
     * Will return not found if not found
     */
    private fun parseMeaning(json: String): String {
        return try {
            val array = JSONArray(json)
            val firstEntry = array.getJSONObject(0)
            val meanings = firstEntry.getJSONArray("meanings")  // fixed - to =
            val firstMeaning = meanings.getJSONObject(0)
            val definitions = firstMeaning.getJSONArray("definitions")
            definitions.getJSONObject(0).getString("definition")
        } catch (e: Exception) {
            "Meaning not found"
        }
    }

    override fun onDestroy() {
        super.onDestroy()
        // Clean up the HTTP client when the activity is destroyed
        httpClient.close()
    }
}